package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Badanie generated by hbm2java
 */
public class Badanie implements java.io.Serializable {

  // Fields    

  private long      idBadan;
  private Rodzbad   rodzbad;
  private Przyjecie przyjecie;
  private Date      data = new Date();
  private String    opis;
  private String    uwagi;

  // Constructors

  /** default constructor */
  public Badanie() {
  }

  /** minimal constructor */
  public Badanie(long idBadan, Przyjecie przyjecie) {
    this.idBadan = idBadan;
    this.przyjecie = przyjecie;
  }
  /** full constructor */
  public Badanie(long idBadan, Rodzbad rodzbad, Przyjecie przyjecie,
      Date data, String opis, String uwagi) {
    this.idBadan = idBadan;
    this.rodzbad = rodzbad;
    this.przyjecie = przyjecie;
    this.data = data;
    this.opis = opis;
    this.uwagi = uwagi;
  }

  // Property accessors
  public long getIdBadan() {
    return this.idBadan;
  }

  public void setIdBadan(long idBadan) {
    this.idBadan = idBadan;
  }
  public Rodzbad getRodzbad() {
    return this.rodzbad;
  }

  public void setRodzbad(Rodzbad rodzbad) {
    this.rodzbad = rodzbad;
  }
  public Przyjecie getPrzyjecie() {
    return this.przyjecie;
  }

  public void setPrzyjecie(Przyjecie przyjecie) {
    this.przyjecie = przyjecie;
  }
  public Date getData() {
    return this.data;
  }

  public void setData(Date data) {
    this.data = data;
  }
  public String getOpis() {
    return this.opis;
  }

  public void setOpis(String opis) {
    this.opis = opis;
  }
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  } 
  
  /** */
  public String toString() {
    java.text.SimpleDateFormat dateFormat = 
      new java.text.SimpleDateFormat("dd.MM.yyyy");
    String tmp = "";
    //tmp += (new Long(this.getIdBadan())).toString() + " , " ;
    //tmp += this.getData().toString()    + "  " ;
    if ( getData() != null ) {
      tmp += dateFormat.format( this.getData() ) + "  " ;
    }     
    if ( getRodzbad() != null ) {
      tmp += getRodzbad().toString() + "  " ;
    }      
    //tmp += getOpis() + "" ;
    //tmp += this.getUwagi()              + " ; " ;    
    return tmp; 
  }
  
  /** */
  public String toStringHtml() {
    java.text.SimpleDateFormat dateFormat = 
      new java.text.SimpleDateFormat("dd.MM.yyyy");
    String tmp = "";    
    tmp += "<table class = \"rap\">";
    tmp += "<tr class = \"rap\">";    
    if ( getData() != null ) {
      tmp += "<td class = \"rap\">"; 
      tmp += dateFormat.format( this.getData() ) + "</td>";
    }     
    if ( getRodzbad() != null ) {
      tmp += "<td class = \"rap\">";
      tmp += getRodzbad().toString() + "</td>";
    }      
    if ( getOpis() != null ) {
      if ( !getOpis().trim().equals("") ) {
        tmp += "<td class = \"rap\">";
        tmp += getOpis() + "</td>";
      }  
    }  
    if ( getUwagi() != null ) {
      if ( !getUwagi().trim().equals("") ) {
        tmp += "<td class = \"rap\">";
        tmp += this.getUwagi() + "</td>" ;
      }  
    }  
    tmp += "</tr></table>\n";
    return tmp; 
  }

}
