package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Leczenie generated by hbm2java
 */
public class Leczenie implements java.io.Serializable {

  // Fields    

  private long      idLecz;
  private Przyjecie przyjecie;
  private Rodzlecz  rodzlecz;
  private Date      data = new Date();
  private String    opis;
  private String    uwagi;

  // Constructors

  /** default constructor */
  public Leczenie() {
  }

  /** minimal constructor */
  public Leczenie(long idLecz, Przyjecie przyjecie) {
    this.idLecz    = idLecz;
    this.przyjecie = przyjecie;
  }
  /** full constructor */
  public Leczenie(long idLecz, Przyjecie przyjecie,
      Rodzlecz rodzlecz, Date data, String opis, String uwagi) {
    this.idLecz    = idLecz;
    this.przyjecie = przyjecie;
    this.rodzlecz  = rodzlecz;
    this.data      = data;
    this.opis      = opis;
    this.uwagi     = uwagi;
  }

  // Property accessors
  public long getIdLecz() {
    return this.idLecz;
  }

  public void setIdLecz(long idLecz) {
    this.idLecz = idLecz;
  }
  public Przyjecie getPrzyjecie() {
    return this.przyjecie;
  }

  public void setPrzyjecie(Przyjecie przyjecie) {
    this.przyjecie = przyjecie;
  }
  public Rodzlecz getRodzlecz() {
    return this.rodzlecz;
  }

  public void setRodzlecz(Rodzlecz rodzlecz) {
    this.rodzlecz = rodzlecz;
  }
  public Date getData() {
    return this.data;
  }

  public void setData(Date data) {
    this.data = data;
  }
  public String getOpis() {
    return this.opis;
  }

  public void setOpis(String opis) {
    this.opis = opis;
  }
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  }
  
  /** */
  public String toString() {
    java.text.SimpleDateFormat dateFormat = 
      new java.text.SimpleDateFormat("dd.MM.yyyy");
    String tmp = "";
    //tmp += (new Long(this.getIdLecz())).toString() + " , " ;
    //tmp += this.getData().toString()     + "  " ;
    if ( this.getData() != null ) {
      tmp += dateFormat.format( this.getData() ) + "  " ;
    }
    if ( this.getRodzlecz() != null ) {
      tmp += this.getRodzlecz().toString() + "  " ;
    }  
    //tmp += this.getOpis()                + "" ;
    //tmp += this.getUwagi()               + " ; " ;    
    return tmp; 
  }
  
  /** */
  public String toStringHtml() {
    java.text.SimpleDateFormat dateFormat = 
      new java.text.SimpleDateFormat("dd.MM.yyyy");
    String tmp = "";    
    tmp += "<table class = \"rap\">";
    tmp += "<tr class = \"rap\">";    
    if ( getData() != null ) {
      tmp += "<td class = \"rap\">"; 
      tmp += dateFormat.format( this.getData() ) + "</td>";
    }     
    if ( getRodzlecz() != null ) {
      tmp += "<td class = \"rap\">";
      tmp += getRodzlecz().toString() + "</td>";
    }      
    if ( getOpis() != null ) {
      if ( !getOpis().trim().equals("") ) {
        tmp += "<td class = \"rap\">";
        tmp += getOpis() + "</td>";
      }  
    }  
    if ( getUwagi() != null ) {
      if ( !getUwagi().trim().equals("") ) {
        tmp += "<td class = \"rap\">";
        tmp += this.getUwagi() + "</td>" ;
      }  
    }  
    tmp += "</tr></table>\n";
    return tmp; 
  }

}
