package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

import java.util.*;

/**
 * Pacjent generated by hbm2java
 *
 * @author  janusz.swol@lot.pl
 */
public class Pacjent implements java.io.Serializable {

  // Fields    

  private long   idPacj;
  private Kasach kasach;
  private Long   pesel;
  private String imie;
  private String nazwisko;
  private Double wiek;
  private String adres;
  private String kontakt;
  private String telkont;
  private String uwagi;
  private Set    przyjecies = new HashSet(0);

  // Constructors

  /** default constructor */
  public Pacjent() {
  }

  /** minimal constructor */
  public Pacjent(long idPacj, String nazwisko) {
    this.idPacj   = idPacj;
    this.nazwisko = nazwisko;
  }
  /** full constructor */
  public Pacjent(long idPacj, Kasach kasach, Long pesel, String imie,
      String nazwisko, Double wiek, String adres, String kontakt,
      String telkont, String uwagi, Set przyjecies) {
    this.idPacj   = idPacj;
    this.kasach   = kasach;
    this.pesel    = pesel;
    this.imie     = imie;
    this.nazwisko = nazwisko;
    this.wiek     = wiek;
    this.adres    = adres;
    this.kontakt  = kontakt;
    this.telkont  = telkont;
    this.uwagi    = uwagi;
    // Set
    this.przyjecies = przyjecies;
  }

  // Property accessors
  public long getIdPacj() {
    return this.idPacj;
  }

  public void setIdPacj(long idPacj) {
    this.idPacj = idPacj;
  }
  
  public Kasach getKasach() {
    return this.kasach;
  }

  public void setKasach(Kasach kasach) {
    this.kasach = kasach;
  }
  
  public Long getPesel() {
    return this.pesel;
  }  
  
  public void setPesel(Long pesel) {
    this.pesel = pesel;
  }  
  
  public String getImie() {
    return this.imie;
  }

  public void setImie(String imie) {
    this.imie = imie;  }
  
  public String getNazwisko() {
    return this.nazwisko;
  }

  public void setNazwisko(String nazwisko) {
    this.nazwisko = nazwisko;
  }
  
  public Double getWiek() {
    return this.wiek;
  }  
  
  public void setWiek(Double wiek) {
    this.wiek = wiek;    
  }  
  
  public String getAdres() {
    return this.adres;
  }

  public void setAdres(String adres) {
    this.adres = adres;
  }
  public String getKontakt() {
    return this.kontakt;
  }

  public void setKontakt(String kontakt) {
    this.kontakt = kontakt;
  }
  
  public String getTelkont() {
    return this.telkont;
  }

  public void setTelkont(String telkont) {
    this.telkont = telkont;
  }
  
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  }
  
  public Set getPrzyjecies() {
    return this.przyjecies;
  }

  public void setPrzyjecies(Set przyjecies) {
    this.przyjecies = przyjecies;
  }
  
  /** */
  public String toString() {
    String tmp = "";
    //tmp += (new Long(this.getIdPacj())).toString() + " , " ;
    if (  this.getPesel() != null ) {
      tmp += this.getPesel().toString()  + "  " ;
    }  
    if (  this.getNazwisko() != null ) {
      tmp += this.getNazwisko()          + "  " ;
    }  
    if (  this.getImie() != null ) {
      tmp += this.getImie()              + "  " ;
    }  
    //tmp += this.getUwagi()             + " , " ;
    //tmp += this.getKasach().toString() + " \n" ;
    /*
    Iterator iter = getPrzyjecies().iterator(); 
    while ( iter.hasNext() ) {      
      tmp += ((Przyjecie)iter.next()) + "\n";                        
    }
    */
    return tmp; 
  }
  
  /** */
  public String toStringHtml() {
    String tmp = "<table class = \"rap\">";
    //tmp += (new Long(this.getIdPacj())).toString() + " , " ;
    if (  this.getPesel() != null ) {
      tmp += "<tr class = \"rap\"><td class = \"rap\">" + 
             this.getPesel().toString()  + "</td>";
    }  
    if (  this.getNazwisko() != null ) {
      tmp += "<td class = \"rap\"><b>" + 
             this.getNazwisko() + "</b></td>";
    }  
    if (  this.getImie() != null ) {
      tmp += "<td class = \"rap\">" + this.getImie() + "</td>";
    } 
    if ( this.getWiek() != null ) {
      tmp += "<td class = \"rap\">" + 
             "<i>Wiek</i> : " + this.getWiek().toString() + "</td>" ;
    } 
    if ( this.getKasach() != null ) {
      tmp += "<td class = \"rap\">" + 
             this.getKasach().toString() + "</td>" ;
    }  
    tmp += "</tr></table>\n";   
    tmp += "<table class = \"rap\"><tr class = \"rap\">";
    if ( this.getAdres() != null ) {
      if ( !this.getAdres().trim().equals("") ) {
        tmp += "<td class = \"rap\">" + this.getAdres() + "</td>" ;
      }  
    }
    if ( this.getTelkont() != null ) {
      if ( !this.getTelkont().trim().equals("") ) {
        tmp += "<td class = \"rap\">" + this.getTelkont() + "</td>" ;
      }  
    }
    if ( this.getKontakt() != null ) {
      if ( !this.getKontakt().trim().equals("") ) {
        tmp += "<td class = \"rap\">" + this.getKontakt() + "</td>" ;
      }  
    }
    tmp += "</tr></table>\n";
    return tmp; 
  }

}
