package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Rodzbad generated by hbm2java
 */
public class Rodzbad implements java.io.Serializable {

  // Fields    

  private long   idRodzb;
  private String opis;
  private String uwagi;
  private Set    badanies = new HashSet(0);

  // Constructors

  /** default constructor */
  public Rodzbad() {
  }

  /** minimal constructor */
  public Rodzbad(long idRodzb) {
    this.idRodzb = idRodzb;
  }
  /** full constructor */
  public Rodzbad(long idRodzb, String opis, String uwagi, Set badanies) {
    this.idRodzb = idRodzb;
    this.opis = opis;
    this.uwagi = uwagi;
    this.badanies = badanies;
  }

  // Property accessors
  public long getIdRodzb() {
    return this.idRodzb;
  }

  public void setIdRodzb(long idRodzb) {
    this.idRodzb = idRodzb;
  }
  public String getOpis() {
    return this.opis;
  }

  public void setOpis(String opis) {
    this.opis = opis;
  }
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  }
  public Set getBadanies() {
    return this.badanies;
  }

  public void setBadanies(Set badanies) {
    this.badanies = badanies;
  }
  
  /** */
  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if ( !( other instanceof Rodzbad ) )
      return false;    
    Rodzbad castOther = (Rodzbad) other;
    // Wystarczy porównaæ identyfikator
    return  ( ( this.getIdRodzb() == castOther.getIdRodzb() ) );
  }
  
  /** */
  public String toString() {
    String tmp = "";  
    //tmp += (new Long(this.getIdRodzb())).toString() + " , " ;
    tmp += this.getOpis()  + "   " ;    
    //tmp += this.getUwagi() + "" ;    
    return tmp; 
  }

}
