package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

/**
 * Rozpoznanie generated by hbm2java
 */
public class Rozpoznanie implements java.io.Serializable {

  // Fields    

  private long   idRozp;
  private String opis;
  private String uwagi;

  // Constructors

  /** default constructor */
  public Rozpoznanie() {
  }

  /** minimal constructor */
  public Rozpoznanie(long idRozp) {
    this.idRozp = idRozp;
  }
  /** full constructor */
  public Rozpoznanie(long idRozp, String opis, String uwagi) {
    this.idRozp = idRozp;
    this.opis = opis;
    this.uwagi = uwagi;
  }

  // Property accessors
  public long getIdRozp() {
    return this.idRozp;
  }

  public void setIdRozp(long idRozp) {
    this.idRozp = idRozp;
  }
  public String getOpis() {
    return this.opis;
  }

  public void setOpis(String opis) {
    this.opis = opis;
  }
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  }
  
  /** */
  public String toString() {
    String tmp = "";
    //tmp += (new Long(this.getIdRozp())).toString() + " , " ;
    tmp += this.getOpis()  + "   " ;
    //tmp += this.getUwagi() + "" ;
    return tmp;    
  }

}
