package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

/**
 * Skierow generated by hbm2java
 */
public class Skierow implements java.io.Serializable {

  // Fields    

  private long   idSkier;
  private String opis = "?"; // w tabeli jest NOT NULL
  private String uwagi;

  // Constructors

  /** default constructor */
  public Skierow() {
  }

  /** minimal constructor */
  public Skierow(long idSkier, String opis) {
    this.idSkier = idSkier;
    this.opis = opis;
  }
  /** full constructor */
  public Skierow(long idSkier, String opis, String uwagi) {
    this.idSkier = idSkier;
    this.opis = opis;
    this.uwagi = uwagi;
  }

  // Property accessors
  public long getIdSkier() {
    return this.idSkier;
  }

  public void setIdSkier(long idSkier) {
    this.idSkier = idSkier;
  }
  public String getOpis() {
    return this.opis;
  }

  public void setOpis(String opis) {
    this.opis = opis;
  }
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  }
  
  /** */
  public String toString() {
    String tmp = ""; 
    //tmp += (new Long(this.getIdSkier())).toString() + " , " ;
    tmp += this.getOpis()  + "   " ;
    //tmp += this.getUwagi() + "" ;
    return tmp;    
  }  

}
