/*
 * KasachJPanel.java
 *
 * Created on 18 grudzieñ 2006, 14:33
 */
package okl.jspacjent.guiswing;

import java.util.*;
import javax.swing.*;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

import okl.jspacjent.model.*;
import okl.jspacjent.dao.*;

/**
 *
 * @author  janusz.swol@lot.pl
 */
public class KasachJPanel extends javax.swing.JPanel {
  
  // Fields  
  
  /** data access object for this application */
  private DAO dao;
  
  /** lista elementów do edycji */
  private List kasy;
  
  /** edytowany bean */
  private Kasach kasach; 
  
  /** model listy elementów do edycji dla komponentu JList */
  private DefaultListModel listModel = new DefaultListModel();  
  

  // Access methods
  
  public void setDao( DAO dao ) {
    this.dao = dao;
  }
  
  public DAO getDao() {
    return dao;
  }
  
  public List getKasy() {
    return kasy;
  }
  
  public void setKasy( List kasy ) {
    this.kasy = kasy;
  }  
  
  public Kasach getKasach() {
    return this.kasach;
  } 
  
  public void setKasach( Kasach kasach ) {
    this.kasach = kasach;
  }
  
  // Other metods
  
  /** wybrany z listy element */
  public Kasach getKasachSelected() {
    return (Kasach)editedList.getSelectedValue();         
  }
  
  /** ustawienie elementu wybranego z listy jako edytowanego */
  public void setKasach() {    
    this.kasach = getKasachSelected();         
  }  
  
  /** odœwie¿enie zawartoœci elementów GUI */
  public void updateComponents() {
    if ( getKasach() == null ) {
      opisField.setText( null );      
      uwagiField.setText( null );
      opisField.setEnabled( false );
      uwagiField.setEnabled( false );
      deleteButton.setEnabled( false );
      updateButton.setEnabled( false );
    }
    else {
      opisField.setEnabled( true );
      uwagiField.setEnabled( true );
      opisField.setText( getKasach().getOpis() );      
      uwagiField.setText( getKasach().getUwagi() );
      deleteButton.setEnabled( true );
      updateButton.setEnabled( true );
    }  
  }
  
  /** wpisanie edytowanych wartoœci do obiektu */
  public void updateKasach() {
    if ( getKasach() != null ) {
      getKasach().setOpis( opisField.getText().trim() );
      getKasach().setUwagi( uwagiField.getText().trim() );
    }  
  }
  
  /** utworzenie modelu listy */
  public void setListModel() {
    listModel.removeAllElements();
    if ( getKasy() == null ) {
      Kasach a = new Kasach();
      setKasy( new LinkedList() );
      getKasy().add( a );
      listModel.addElement( a ); 
    }
    else {
      Iterator iter = getKasy().iterator();
      while ( iter.hasNext() ) {
        listModel.addElement( iter.next() );
      }
    }
  }
  
  // Constructors  
  
  /** Creates new form KasachJPanel */
  public KasachJPanel() {
    initComponents();
    updateComponents();
  }
  
  /** Creates new form KasachJPanel */
  public KasachJPanel( List kasy ) {
    setKasy( kasy );
    initComponents();
    updateComponents();
  }
  
  /** Creates new form KasachJPanel */
  public KasachJPanel( DAO dao ) {
    setDao( dao );
    setKasy( dao.getAllKasach() );
    initComponents();
    updateComponents();
  }
  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    setListModel();
    listPanel = new javax.swing.JPanel();
    jScrollPane = new javax.swing.JScrollPane();
    editedList = new javax.swing.JList( listModel );
    editPanel = new javax.swing.JPanel();
    opisField = new javax.swing.JTextField();
    uwagiField = new javax.swing.JTextField();
    buttonPanel = new javax.swing.JPanel();
    deleteButton = new javax.swing.JButton();
    addButton = new javax.swing.JButton();
    updateButton = new javax.swing.JButton();

    listPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wyb\u00f3r kasy chorych", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));
    editedList.setFont(new java.awt.Font("Tahoma", 0, 12));
    editedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    editedList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        editedListValueChanged(evt);
      }
    });

    jScrollPane.setViewportView(editedList);

    org.jdesktop.layout.GroupLayout listPanelLayout = new org.jdesktop.layout.GroupLayout(listPanel);
    listPanel.setLayout(listPanelLayout);

    editPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edycja kasy chorych", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));
    opisField.setFont(new java.awt.Font("Tahoma", 0, 12));
    opisField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));

    uwagiField.setFont(new java.awt.Font("Tahoma", 0, 12));
    uwagiField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Symbol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));

    org.jdesktop.layout.GroupLayout editPanelLayout = new org.jdesktop.layout.GroupLayout(editPanel);
    editPanel.setLayout(editPanelLayout);

    buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operacje na elementach listy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));
    deleteButton.setFont(new java.awt.Font("Tahoma", 0, 12));
    deleteButton.setForeground(new java.awt.Color(153, 0, 0));
    deleteButton.setText("Usu\u0144 zaznaczon\u0105");
    deleteButton.setToolTipText("usuni\u0119cie elementu wybranego na li\u015bcie ");
    deleteButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteButtonActionPerformed(evt);
      }
    });

    addButton.setFont(new java.awt.Font("Tahoma", 0, 12));
    addButton.setForeground(new java.awt.Color(0, 102, 51));
    addButton.setText("Dodaj now¹");
    addButton.setToolTipText("dodanie nowego elementu do listy ");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });

    updateButton.setFont(new java.awt.Font("Tahoma", 0, 12));
    updateButton.setText("Wpisz edytowan\u0105");
    updateButton.setToolTipText("wpisanie edytowanych ni\u017cej warto\u015bci na list\u0119");
    updateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(buttonPanel);
    buttonPanel.setLayout(buttonPanelLayout);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    editPanelLayout.setHorizontalGroup(
      editPanelLayout.createParallelGroup(GroupLayout.TRAILING)
        .add(editPanelLayout.createSequentialGroup()
          .addContainerGap()
          .add(opisField, GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
          .addPreferredGap(LayoutStyle.RELATED)
          .add(uwagiField, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
          .addContainerGap())
    );
    editPanelLayout.setVerticalGroup(
      editPanelLayout.createParallelGroup(GroupLayout.LEADING)
        .add(editPanelLayout.createSequentialGroup()
          .addContainerGap()
          .add(editPanelLayout.createParallelGroup(GroupLayout.BASELINE)
            .add(uwagiField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .add(opisField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    listPanelLayout.setHorizontalGroup(
      listPanelLayout.createParallelGroup(GroupLayout.LEADING)
        .add(listPanelLayout.createSequentialGroup()
          .addContainerGap()
          .add(jScrollPane, GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
          .addContainerGap())
    );
    listPanelLayout.setVerticalGroup(
      listPanelLayout.createParallelGroup(GroupLayout.LEADING)
        .add(listPanelLayout.createSequentialGroup()
          .add(jScrollPane, GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
          .addContainerGap())
    );
    buttonPanelLayout.setHorizontalGroup(
      buttonPanelLayout.createParallelGroup(GroupLayout.LEADING)
        .add(buttonPanelLayout.createSequentialGroup()
          .addContainerGap()
          .add(buttonPanelLayout.createParallelGroup(GroupLayout.LEADING)
            .add(deleteButton, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .add(addButton, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .add(updateButton, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
          .addContainerGap())
    );
    buttonPanelLayout.setVerticalGroup(
      buttonPanelLayout.createParallelGroup(GroupLayout.LEADING)
        .add(buttonPanelLayout.createSequentialGroup()
          .addContainerGap()
          .add(deleteButton)
          .addPreferredGap(LayoutStyle.RELATED)
          .add(addButton)
          .addPreferredGap(LayoutStyle.RELATED)
          .add(updateButton)
          .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setHorizontalGroup(
      layout.createParallelGroup(GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
          .addContainerGap()
          .add(layout.createParallelGroup(GroupLayout.TRAILING)
            .add(editPanel, GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
              .add(listPanel, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
              .addPreferredGap(LayoutStyle.RELATED)
              .add(buttonPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
          .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
          .add(layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
              .add(79, 79, 79)
              .add(buttonPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
              .addContainerGap()
              .add(listPanel, GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
          .addPreferredGap(LayoutStyle.RELATED)
          .add(editPanel, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
          .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    // ...
    setKasach( new Kasach() );
    if ( getKasy() != null ) {
      getKasy().add( getKasach() );
    }  
    listModel.addElement( getKasach() );    
    updateComponents();
    editedList.setSelectedValue( getKasach(), true );        
    if ( ( getKasach() != null ) && ( getDao() != null ) ){
      dao.updateKasach( getKasach() );
    }  
  }//GEN-LAST:event_addButtonActionPerformed

  private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    // ...
    if ( ( getKasach() != null ) && ( getDao() != null ) ) {      
      dao.deleteKasach( getKasach() );      
    }
    if ( ( getKasy() != null ) && ( getKasach() != null ) ) {
      getKasy().remove( getKasach() );
    }  
    if (  getKasachSelected() != null ) {
      listModel.removeElement( getKasachSelected() );
    }              
    editedList.updateUI();
        
  }//GEN-LAST:event_deleteButtonActionPerformed

  private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    // ...
    this.updateKasach(); 
    if ( ( getDao() != null ) && ( getKasach() != null ) ) {
      dao.updateKasach( getKasach() );
    }  
    editedList.updateUI();   
  }//GEN-LAST:event_updateButtonActionPerformed

  private void editedListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_editedListValueChanged
    // ...
    setKasach();  
    updateComponents();
    opisField.requestFocus();
  }//GEN-LAST:event_editedListValueChanged
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JButton deleteButton;
  private javax.swing.JPanel editPanel;
  private javax.swing.JList editedList;
  private javax.swing.JScrollPane jScrollPane;
  private javax.swing.JPanel listPanel;
  private javax.swing.JTextField opisField;
  private javax.swing.JButton updateButton;
  private javax.swing.JTextField uwagiField;
  // End of variables declaration//GEN-END:variables
  
}
