/*
 * LekarzJPanel.java
 *
 * Created on 18 grudzieñ 2006, 14:33
 */
package okl.jspacjent.guiswing;

import java.util.*;
import javax.swing.*;

import okl.jspacjent.model.*;
import okl.jspacjent.dao.*;

/** 
 *
 * @author  janusz.swol@lot.pl
 */
public class LekarzJPanel extends javax.swing.JPanel {
  
  // Fields  
  
  /** data access object for this application */
  private DAO dao;
  
  /** lista elementów do edycji */
  private List lekarze;
  
  /** edytowany bean */
  private Lekarz lekarz; 
  
  /** model listy elementów do edycji dla komponentu JList */
  private DefaultListModel listModel = new DefaultListModel();  
  

  // Access methods
  
  public void setDao( DAO dao ) {
    this.dao = dao;
  }
  
  public DAO getDao() {
    return dao;
  }
  
  public List getLekarze() {
    return lekarze;
  }
  
  public void setLekarze( List lekarze ) {
    this.lekarze = lekarze;
  }  
  
  public Lekarz getLekarz() {
    return this.lekarz;
  } 
  
  public void setLekarz( Lekarz lekarz ) {
    this.lekarz = lekarz;
  }
  
  // Other metods
  
  /** wybrany z listy element */
  public Lekarz getLekarzSelected() {
    return (Lekarz)editedList.getSelectedValue();         
  }
  
  /** ustawienie elementu wybranego z listy jako edytowanego */
  public void setLekarz() {    
    this.lekarz = getLekarzSelected();         
  }  
  
  /** odœwie¿enie zawartoœci elementów GUI */
  public void updateComponents() {
    if ( getLekarz() == null ) {
      imieField.setText( null );      
      nazwiskoField.setText( null );      
      uwagiField.setText( null );
      imieField.setEnabled( false );
      nazwiskoField.setEnabled( false );
      uwagiField.setEnabled( false );
      deleteButton.setEnabled( false );
      updateButton.setEnabled( false );
    }
    else {
      imieField.setEnabled(true);
      nazwiskoField.setEnabled( true );
      uwagiField.setEnabled( true );
      imieField.setText( getLekarz().getImie() );      
      nazwiskoField.setText( getLekarz().getNazwisko() );      
      uwagiField.setText( getLekarz().getUwagi() );
      deleteButton.setEnabled( true );
      updateButton.setEnabled( true );
    }  
  }
  
  /** wpisanie edytowanych wartoœci do obiektu */
  public void updateLekarz() {
    if ( getLekarz() != null ) {
      getLekarz().setImie( imieField.getText() );
      getLekarz().setNazwisko( nazwiskoField.getText().trim() );
      getLekarz().setUwagi( uwagiField.getText().trim() );
    }  
  }
  
  /** utworzenie modelu listy */
  public void setListModel() {
    listModel.removeAllElements();
    if ( getLekarze() == null ) {
      Lekarz a = new Lekarz();
      setLekarze( new LinkedList() );
      getLekarze().add( a );
      listModel.addElement( a ); 
    }
    else {
      Iterator iter = getLekarze().iterator();
      while ( iter.hasNext() ) {
        Lekarz a = (Lekarz)iter.next();
        listModel.addElement(a);        
      }      
    }
  }
  
  // Constructors  
  
  /** Creates new form LekarzJPanel */
  public LekarzJPanel() {
    initComponents();
    updateComponents();
  }
  
  /** Creates new form LekarzJPanel */
  public LekarzJPanel( List lekarze ) {
    setLekarze( lekarze );
    initComponents();
    updateComponents();
  }
  
  /** Creates new form LekarzJPanel */
  public LekarzJPanel( DAO dao ) {
    setDao( dao );
    setLekarze( dao.getAllLekarz() );
    initComponents();
    updateComponents();
  }
  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    setListModel();
    listPanel = new javax.swing.JPanel();
    jScrollPane = new javax.swing.JScrollPane();
    editedList = new javax.swing.JList( listModel );
    editPanel = new javax.swing.JPanel();
    imieField = new javax.swing.JTextField();
    nazwiskoField = new javax.swing.JTextField();
    uwagiField = new javax.swing.JTextField();
    buttonPanel = new javax.swing.JPanel();
    deleteButton = new javax.swing.JButton();
    addButton = new javax.swing.JButton();
    updateButton = new javax.swing.JButton();

    listPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wyb\u00f3r lekarza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));
    editedList.setFont(new java.awt.Font("Tahoma", 0, 12));
    editedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    editedList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        editedListValueChanged(evt);
      }
    });

    jScrollPane.setViewportView(editedList);

    org.jdesktop.layout.GroupLayout listPanelLayout = new org.jdesktop.layout.GroupLayout(listPanel);
    listPanel.setLayout(listPanelLayout);
    listPanelLayout.setHorizontalGroup(
      listPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(listPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(jScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        .addContainerGap())
    );
    listPanelLayout.setVerticalGroup(
      listPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, listPanelLayout.createSequentialGroup()
        .add(jScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        .addContainerGap())
    );

    editPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edycja danych lekarza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));
    imieField.setFont(new java.awt.Font("Tahoma", 0, 12));
    imieField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imi\u0119", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));

    nazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 12));
    nazwiskoField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nazwisko", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));

    uwagiField.setFont(new java.awt.Font("Tahoma", 0, 12));
    uwagiField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Uwagi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));

    org.jdesktop.layout.GroupLayout editPanelLayout = new org.jdesktop.layout.GroupLayout(editPanel);
    editPanel.setLayout(editPanelLayout);
    editPanelLayout.setHorizontalGroup(
      editPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(editPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(imieField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(nazwiskoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(uwagiField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        .addContainerGap())
    );
    editPanelLayout.setVerticalGroup(
      editPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, editPanelLayout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(editPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(imieField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(nazwiskoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(uwagiField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operacje na elementach listy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")));
    deleteButton.setFont(new java.awt.Font("Tahoma", 0, 12));
    deleteButton.setForeground(new java.awt.Color(153, 0, 0));
    deleteButton.setText("Usu\u0144 zaznaczony");
    deleteButton.setToolTipText("usuni\u0119cie elementu wybranego na li\u015bcie ");
    deleteButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteButtonActionPerformed(evt);
      }
    });

    addButton.setFont(new java.awt.Font("Tahoma", 0, 12));
    addButton.setForeground(new java.awt.Color(0, 102, 51));
    addButton.setText("Dodaj nowy");
    addButton.setToolTipText("dodanie nowego elementu do listy ");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });

    updateButton.setFont(new java.awt.Font("Tahoma", 0, 12));
    updateButton.setText("Wpisz edytowany");
    updateButton.setToolTipText("wpisanie edytowanych ni\u017cej warto\u015bci na list\u0119");
    updateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(buttonPanel);
    buttonPanel.setLayout(buttonPanelLayout);
    buttonPanelLayout.setHorizontalGroup(
      buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(buttonPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(deleteButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
          .add(addButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
          .add(updateButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        .addContainerGap())
    );
    buttonPanelLayout.setVerticalGroup(
      buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(buttonPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(deleteButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(addButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(updateButton)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, editPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(listPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(listPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(editPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    // ...
    setLekarz( new Lekarz() );
    if ( getLekarze() != null ) {
      getLekarze().add( getLekarz() );
    }  
    listModel.addElement( getLekarz() );    
    updateComponents();
    editedList.setSelectedValue( getLekarz(), true );        
    if ( ( getLekarz() != null ) && ( getDao() != null ) ){
      dao.updateLekarz( getLekarz() );
    }  
  }//GEN-LAST:event_addButtonActionPerformed

  private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    // ...
    if ( ( getLekarz() != null ) && ( getDao() != null ) ) {      
      dao.deleteLekarz( getLekarz() );      
    }
    if ( ( getLekarze() != null ) && ( getLekarz() != null ) ) {
      getLekarze().remove( getLekarz() );
    }  
    if (  getLekarzSelected() != null ) {
      listModel.removeElement( getLekarzSelected() );
    }              
    editedList.updateUI();
        
  }//GEN-LAST:event_deleteButtonActionPerformed

  private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    // ...
    this.updateLekarz();
    if ( ( getDao() != null ) && ( getLekarz() != null ) ) {
      dao.updateLekarz( getLekarz() );
    }  
    editedList.updateUI();   
  }//GEN-LAST:event_updateButtonActionPerformed

  private void editedListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_editedListValueChanged
    // ...
    setLekarz();  
    updateComponents();
    imieField.requestFocus();
  }//GEN-LAST:event_editedListValueChanged
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JButton deleteButton;
  private javax.swing.JPanel editPanel;
  private javax.swing.JList editedList;
  private javax.swing.JTextField imieField;
  private javax.swing.JScrollPane jScrollPane;
  private javax.swing.JPanel listPanel;
  private javax.swing.JTextField nazwiskoField;
  private javax.swing.JButton updateButton;
  private javax.swing.JTextField uwagiField;
  // End of variables declaration//GEN-END:variables
  
}
