/*
 * PacjentUI.java
 *
 * Created on 11 grudzieñ 2006, 15:27
 */
package okl.jspacjent.guiswing;

import java.text.*;
import javax.swing.*;

import okl.jspacjent.model.*;

/**
 *
 * @author  JS
 */
public class PacjentDialogUI extends javax.swing.JDialog {
  /** A return status code - returned if Cancel button has been pressed */
  public static final int RET_CANCEL = 0;
  /** A return status code - returned if OK button has been pressed */
  public static final int RET_OK = 1;  
  
  /** @return the return status of this dialog - 
   *          one of RET_OK or RET_CANCEL          */
  public int getReturnStatus() {
    return returnStatus;
  }  
  
  public void setPacjentPanel( PacjentJPanel pacjentPanel ) {
    this.pacjentPanel = pacjentPanel;  
  }
  
  public PacjentJPanel getPacjentPanel() {        
    return this.pacjentPanel;
  }
  
  public PacjentJPanel getOrCreatePacjentPanel() {
    if ( getPacjentPanel() == null ) {
      setPacjentPanel( new PacjentJPanel() );
    }    
    return this.pacjentPanel;
  }
  
  public void setPrzyjeciePanel( PrzyjecieJPanel przyjeciePanel ) {
    this.przyjeciePanel = przyjeciePanel;  
  }
  
  public PrzyjecieJPanel getPrzyjeciePanel() {        
    return this.przyjeciePanel;
  }
  
  public PrzyjecieJPanel getOrCreatePrzyjeciePanel() {
    if ( getPrzyjeciePanel() == null ) {
      setPrzyjeciePanel( new PrzyjecieJPanel() );
    }    
    return this.przyjeciePanel;
  }  
  
  protected void setUpLookAndFeel() {
    try {
      UIManager.setLookAndFeel(
        UIManager.getSystemLookAndFeelClassName());
    }
    catch ( Exception e ) {
      e.printStackTrace();  
    }
  }
  
  /** Creates new form PacjentUI */
  public PacjentDialogUI(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    setUpLookAndFeel();
    initComponents();
  } 
  
  /** Creates new form PacjentUI */
  public PacjentDialogUI(java.awt.Frame parent, 
                         boolean modal,                         
                         PacjentJPanel pacjentPanel ) {
    super(parent, modal);    
    setPacjentPanel( pacjentPanel );
    setUpLookAndFeel();
    initComponents();   
  }
  
  /** Creates new form PacjentUI */
  public PacjentDialogUI(java.awt.Frame parent, 
                         boolean modal,                         
                         PacjentJPanel   pacjentPanel,
                         PrzyjecieJPanel przyjeciePanel ) {
    super(parent, modal);        
    setPacjentPanel( pacjentPanel );
    setPrzyjeciePanel( przyjeciePanel );
    setUpLookAndFeel();
    initComponents();      
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    pacjentPanelTop = new javax.swing.JPanel();
    pacjentPanel = getOrCreatePacjentPanel();
    przyjeciePanelTop = new javax.swing.JPanel();
    przyjeciePanel = getOrCreatePrzyjeciePanel();

    setTitle("Pacjent");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setName("dialogPacjent");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    okButton.setFont(new java.awt.Font("Tahoma", 0, 14));
    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14));
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout pacjentPanelTopLayout = new org.jdesktop.layout.GroupLayout(pacjentPanelTop);
    pacjentPanelTop.setLayout(pacjentPanelTopLayout);
    pacjentPanelTopLayout.setHorizontalGroup(
      pacjentPanelTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(pacjentPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
    );
    pacjentPanelTopLayout.setVerticalGroup(
      pacjentPanelTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(pacjentPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
    );

    org.jdesktop.layout.GroupLayout przyjeciePanelTopLayout = new org.jdesktop.layout.GroupLayout(przyjeciePanelTop);
    przyjeciePanelTop.setLayout(przyjeciePanelTopLayout);
    przyjeciePanelTopLayout.setHorizontalGroup(
      przyjeciePanelTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, przyjeciePanelTopLayout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .add(przyjeciePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    przyjeciePanelTopLayout.setVerticalGroup(
      przyjeciePanelTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(przyjeciePanelTopLayout.createSequentialGroup()
        .add(przyjeciePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(pacjentPanelTop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(przyjeciePanelTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(okButton)
          .add(cancelButton))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(pacjentPanelTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(przyjeciePanelTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    doClose(RET_OK);    
  }//GEN-LAST:event_okButtonActionPerformed
  
  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    doClose(RET_CANCEL);
  }//GEN-LAST:event_cancelButtonActionPerformed
  
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    doClose(RET_CANCEL);
  }//GEN-LAST:event_closeDialog
  
  private void doClose(int retStatus) {
    if ( retStatus == RET_OK ) {
      try {
        getPacjentPanel().updatePacjentBean();
        getPacjentPanel().saveOrUpdatePacjent();
        //getPacjentPanel().clearComponents();
        //
        getPrzyjeciePanel().updatePrzyjecieBean();
        getPrzyjeciePanel().saveOrUpdatePrzyjecie();
        //        
        //getPrzyjeciePanel().clearComponents();
      }
      catch (ParseException e) {
        System.out.println(e);
      }
    }
    returnStatus = retStatus;
    setVisible(false);
    dispose();
    System.exit(0);
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PacjentDialogUI(
          new javax.swing.JFrame(), true, 
                                    new PacjentJPanel(),
                                    new PrzyjecieJPanel()          
        ).setVisible(true);
      }
    });    
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton okButton;
  private okl.jspacjent.guiswing.PacjentJPanel pacjentPanel;
  private javax.swing.JPanel pacjentPanelTop;
  private okl.jspacjent.guiswing.PrzyjecieJPanel przyjeciePanel;
  private javax.swing.JPanel przyjeciePanelTop;
  // End of variables declaration//GEN-END:variables
  
  private int returnStatus = RET_CANCEL;       
  
}
