/*
 * LekarzlDialog.java
 *
 * Created on 18 grudzieñ 2006, 16:28
 */
package okl.jspacjent.guiswing;

/**
 *
 * @author  JS
 */
public class PacwybJDialog extends javax.swing.JDialog {
  
  /** A return status code - returned if Cancel button has been pressed */
  public static final int RET_CANCEL = 0;
  /** A return status code - returned if OK button has been pressed */
  public static final int RET_OK = 1;
  
  
  public void setPacwybPanel( PacwybJPanel pacwybPanel ) {
    this.pacwybPanel = pacwybPanel;
  }
  
  public PacwybJPanel getPacwybPanel() {
    return this.pacwybPanel;   
  }
  
  public PacwybJPanel getOrCreatePacwybPanel() {
    if ( getPacwybPanel() == null ) {
      return new PacwybJPanel();
    }
    else {
      return getPacwybPanel();
    }  
  }
  
  // Constructors
  
  /** Creates new form LekarzlDialog */
  public PacwybJDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    setPacwybPanel( new PacwybJPanel() );
    initComponents();
  }
  
   /** Creates new form LekarzlDialog */
  public PacwybJDialog(java.awt.Frame parent, 
                            boolean modal,
                            PacwybJPanel pacwybPanel ) {
    super(parent, modal);
    setPacwybPanel( pacwybPanel );
    initComponents();
  }
  
  /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
  public int getReturnStatus() {
    return returnStatus;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    pacwybPanel = getOrCreatePacwybPanel();
    cancelButton = new javax.swing.JButton();
    oklButton = new javax.swing.JButton();
    wyborLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Wyb\u00f3r danych osobowych pacjenta");
    setName("dialogLekarz");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    pacwybPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        pacwybPanelPropertyChange(evt);
      }
    });

    cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14));
    cancelButton.setForeground(new java.awt.Color(153, 0, 0));
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    oklButton.setFont(new java.awt.Font("Tahoma", 0, 14));
    oklButton.setForeground(new java.awt.Color(0, 102, 102));
    oklButton.setText("OK");
    oklButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        oklButtonActionPerformed(evt);
      }
    });

    wyborLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
    wyborLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    wyborLabel.setText("Potwierd\u017a wyb\u00f3r :");
    wyborLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
    wyborLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(org.jdesktop.layout.GroupLayout.TRAILING, pacwybPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(layout.createSequentialGroup()
          .add(184, 184, 184)
          .add(wyborLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(13, 13, 13)
          .add(cancelButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
          .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
          .add(oklButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(pacwybPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 388, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, wyborLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(cancelButton)
          .add(oklButton))
        .addContainerGap())
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void pacwybPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pacwybPanelPropertyChange
  
  }//GEN-LAST:event_pacwybPanelPropertyChange

  private void oklButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oklButtonActionPerformed
    doClose(RET_OK);      
  }//GEN-LAST:event_oklButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    doClose(RET_CANCEL);
  }//GEN-LAST:event_cancelButtonActionPerformed
      
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    doClose(RET_CANCEL);
  }//GEN-LAST:event_closeDialog
  
  private void doClose(int retStatus) {    
    returnStatus = retStatus;
    setVisible(false);
    dispose();
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PacwybJDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton oklButton;
  private okl.jspacjent.guiswing.PacwybJPanel pacwybPanel;
  private javax.swing.JLabel wyborLabel;
  // End of variables declaration//GEN-END:variables
  
  private int returnStatus = RET_CANCEL;
}
