/*
 * LekarzlDialog.java
 *
 * Created on 18 grudzieñ 2006, 16:28
 */
package okl.jspacjent.guiswing;

/**
 *
 * @author  JS
 */
public class PrzywybJDialog extends javax.swing.JDialog {
  
  /** A return status code - returned if Cancel button has been pressed */
  public static final int RET_CANCEL = 0;
  /** A return status code - returned if OK button has been pressed */
  public static final int RET_OK = 1;
  
  
  public void setPrzywybPanel( PrzywybJPanel przywybPanel ) {
    this.przywybPanel = przywybPanel;
  }
  
  public PrzywybJPanel getPrzywybPanel() {
    return this.przywybPanel;   
  }
  
  public PrzywybJPanel getOrCreatePrzywybPanel() {
    if ( getPrzywybPanel() == null ) {
      return new PrzywybJPanel();
    }
    else {
      return getPrzywybPanel();
    }  
  }
  
  // Constructors
  
  /** Creates new form LekarzlDialog */
  public PrzywybJDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    setPrzywybPanel( new PrzywybJPanel() );
    initComponents();
  }
  
   /** Creates new form LekarzlDialog */
  public PrzywybJDialog(java.awt.Frame parent, 
                            boolean modal,
                            PrzywybJPanel przywybPanel ) {
    super(parent, modal);
    setPrzywybPanel( przywybPanel );
    initComponents();
  }
  
  /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
  public int getReturnStatus() {
    return returnStatus;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    przywybPanel = getOrCreatePrzywybPanel();
    cancelButton = new javax.swing.JButton();
    oklButton = new javax.swing.JButton();
    wyborLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Wyb\u00f3r przyj\u0119cia");
    setName("dialogLekarz");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14));
    cancelButton.setForeground(new java.awt.Color(153, 0, 0));
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    oklButton.setFont(new java.awt.Font("Tahoma", 0, 14));
    oklButton.setForeground(new java.awt.Color(0, 102, 102));
    oklButton.setText("OK");
    oklButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        oklButtonActionPerformed(evt);
      }
    });

    wyborLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
    wyborLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    wyborLabel.setText("Potwierd\u017a wyb\u00f3r :");
    wyborLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
    wyborLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(245, 245, 245)
        .add(wyborLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(53, 53, 53)
        .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(oklButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
      .add(przywybPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(przywybPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(wyborLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(cancelButton)
          .add(oklButton))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void oklButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oklButtonActionPerformed
    doClose(RET_OK);      
  }//GEN-LAST:event_oklButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    doClose(RET_CANCEL);
  }//GEN-LAST:event_cancelButtonActionPerformed
      
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    doClose(RET_CANCEL);
  }//GEN-LAST:event_closeDialog
  
  private void doClose(int retStatus) {    
    returnStatus = retStatus;
    setVisible(false);
    dispose();
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PacwybJDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton oklButton;
  private okl.jspacjent.guiswing.PrzywybJPanel przywybPanel;
  private javax.swing.JLabel wyborLabel;
  // End of variables declaration//GEN-END:variables
  
  private int returnStatus = RET_CANCEL;
}
