/*
 * RodzbadlDialog.java
 *
 * Created on 18 grudzieñ 2006, 16:28
 */
package okl.jspacjent.guiswing;

/**
 *
 * @author  JS
 */
public class RodzbadJDialog extends javax.swing.JDialog {
  
  /** A return status code - returned if Cancel button has been pressed */
  public static final int RET_CANCEL = 0;
  /** A return status code - returned if OK button has been pressed */
  public static final int RET_OK = 1;
  
  
  public void setRodzbadPanel( RodzbadJPanel rodzbadPanel ) {
    this.rodzbadPanel = rodzbadPanel;
  }
  
  public RodzbadJPanel getRodzbadPanel() {
    return this.rodzbadPanel;
  }
  
  public RodzbadJPanel getOrCreateRodzbadPanel() {
    if ( getRodzbadPanel() == null ) {
      return new RodzbadJPanel();
    }
    else {
      return getRodzbadPanel();
    }  
  }
  
  // Constructors
  
  /** Creates new form RodzbadlDialog */
  public RodzbadJDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    setRodzbadPanel( new RodzbadJPanel() );
    initComponents();
  }
  
   /** Creates new form RodzbadlDialog */
  public RodzbadJDialog(java.awt.Frame parent, 
                        boolean modal,
                        RodzbadJPanel rodzbadPanel) {
    super(parent, modal);
    setRodzbadPanel( rodzbadPanel );
    initComponents();
  }
  
  /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
  public int getReturnStatus() {
    return returnStatus;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    rodzbadPanel = getOrCreateRodzbadPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Rodzaje bada\u0144");
    setLocationByPlatform(true);
    setModal(true);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(rodzbadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(rodzbadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents
      
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    doClose(RET_CANCEL);
  }//GEN-LAST:event_closeDialog
  
  private void doClose(int retStatus) {    
    returnStatus = retStatus;
    setVisible(false);
    dispose();
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RodzbadJDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private okl.jspacjent.guiswing.RodzbadJPanel rodzbadPanel;
  // End of variables declaration//GEN-END:variables
  
  private int returnStatus = RET_CANCEL;
}
