/*
 * RozpoznanielDialog.java
 *
 * Created on 18 grudzieñ 2006, 16:28
 */
package okl.jspacjent.guiswing;

/**
 *
 * @author  JS
 */
public class RozpoznanieJDialog extends javax.swing.JDialog {
  
  /** A return status code - returned if Cancel button has been pressed */
  public static final int RET_CANCEL = 0;
  /** A return status code - returned if OK button has been pressed */
  public static final int RET_OK = 1;
  
  
  public void setRozpoznaniePanel( RozpoznanieJPanel rozpoznaniePanel ) {
    this.rozpoznaniePanel = rozpoznaniePanel;
  }
  
  public RozpoznanieJPanel getRozpoznaniePanel() {
    return this.rozpoznaniePanel;   
  }
  
  public RozpoznanieJPanel getOrCreateRozpoznaniePanel() {
    if ( getRozpoznaniePanel() == null ) {
      return new RozpoznanieJPanel();
    }
    else {
      return getRozpoznaniePanel();
    }  
  }
  
  // Constructors
  
  /** Creates new form RozpoznanielDialog */
  public RozpoznanieJDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    setRozpoznaniePanel( new RozpoznanieJPanel() );
    initComponents();
  }
  
   /** Creates new form RozpoznanielDialog */
  public RozpoznanieJDialog(java.awt.Frame parent, 
                            boolean modal,
                            RozpoznanieJPanel rozpoznaniePanel) {
    super(parent, modal);
    setRozpoznaniePanel( rozpoznaniePanel );
    initComponents();
  }
  
  /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
  public int getReturnStatus() {
    return returnStatus;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    rozpoznaniePanel = getOrCreateRozpoznaniePanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Rozpoznania");
    setLocationByPlatform(true);
    setModal(true);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 482, Short.MAX_VALUE)
      .add(rozpoznaniePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 342, Short.MAX_VALUE)
      .add(rozpoznaniePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents
      
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    doClose(RET_CANCEL);
  }//GEN-LAST:event_closeDialog
  
  private void doClose(int retStatus) {    
    returnStatus = retStatus;
    setVisible(false);
    dispose();
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RozpoznanieJDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private okl.jspacjent.guiswing.RozpoznanieJPanel rozpoznaniePanel;
  // End of variables declaration//GEN-END:variables
  
  private int returnStatus = RET_CANCEL;
}
